version: "3.7"

services:
  api:
    ports:
      - "8000:8000"
      - "5678:5678"
    command: ["sh", "-c", "python3 -m debugpy --listen 0.0.0.0:5678 /badgr_server/manage.py runserver 0.0.0.0:8000"]