# Generated by Django 2.2.24 on 2021-11-18 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0060_issuer_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='city',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='country',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='street',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='streetnumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='zip',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
