# Generated by Django 2.2.24 on 2021-11-18 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0061_auto_20211118_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='category',
            field=models.CharField(default='n/a', max_length=255),
        ),
    ]
