# Generated by Django 2.2.24 on 2021-11-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0063_auto_20211122_0622'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuer',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issuer',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
