# Generated by Django 3.2 on 2024-08-07 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0065_badgeclass_imageframe'),
    ]

    operations = [
        migrations.CreateModel(
            name='QrCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('title', models.CharField(max_length=254)),
                ('createdBy', models.CharField(max_length=254)),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('expires_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('badgeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='issuer.badgeclass')),
                ('issuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.issuer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RequestedBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('firstName', models.CharField(max_length=254)),
                ('lastName', models.CharField(max_length=254)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('requestedOn', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(default='Pending', max_length=254)),
                ('badgeclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedbadges', to='issuer.badgeclass')),
                ('qrcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestedbadges', to='issuer.qrcode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
