# Generated by Django 2.2.28 on 2024-02-22 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0066_auto_20240220_2344'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collectionbadgecontainer',
            options={'verbose_name': 'Collection Badge'},
        ),
        migrations.AlterModelManagers(
            name='superbadge',
            managers=[
                ('cached', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='collectionbadgecontainer',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/badges'),
        ),
        migrations.AddField(
            model_name='collectionbadgecontainer',
            name='image_hash',
            field=models.CharField(blank=True, default='', max_length=72),
        ),
        migrations.AddField(
            model_name='collectionbadgecontainer',
            name='image_preview',
            field=models.FileField(blank=True, null=True, upload_to='uploads/badges'),
        ),
        migrations.AlterField(
            model_name='collectionbadgecontainer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collectionbadgecontainer',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
