# Generated by Django 2.2.28 on 2024-02-22 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0067_auto_20240222_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='superbadge',
            name='image',
            field=models.FileField(blank=True, upload_to='uploads/badges'),
        ),
        migrations.AddField(
            model_name='superbadge',
            name='image_hash',
            field=models.CharField(blank=True, default='', max_length=72),
        ),
        migrations.AddField(
            model_name='superbadge',
            name='image_preview',
            field=models.FileField(blank=True, null=True, upload_to='uploads/badges'),
        ),
        migrations.AlterField(
            model_name='superbadge',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='superbadge',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
