# Generated by Django 3.2 on 2025-01-16 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0068_issuer_intendeduseverified'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LearningPathParticipant',
        ),
    ]
