# Generated by Django 3.2 on 2024-12-06 09:45
# generate private keys for existing issuers

from django.db import migrations
from issuer.utils import generate_private_key_pem

def issuer_generate_private_key(apps, schema):
    Issuer = apps.get_model('issuer', 'Issuer')
    for issuer in Issuer.objects.all():
        issuer.private_key = generate_private_key_pem()
        issuer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0069_issuer_private_key'),
    ]

    operations = [
        migrations.RunPython(issuer_generate_private_key)
    ]
