# Generated by Django 3.2 on 2025-03-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0069_delete_learningpathparticipant'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='copy_permissions',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]