# Generated by Django 3.2 on 2025-04-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0070_badgeclass_copy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='notifications',
            field=models.BooleanField(default=False),
        ),
    ]
