# Generated by Django 3.2 on 2025-04-28 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issuer', '0074_badgeinstance_ob_json_2_0'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedBadgeAssertion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_version', models.PositiveIntegerField(default=1)),
                ('entity_id', models.CharField(default=None, max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('source', models.CharField(default='local', max_length=254)),
                ('source_url', models.CharField(blank=True, default=None, max_length=254, null=True, unique=True)),
                ('badge_name', models.CharField(max_length=255)),
                ('badge_description', models.TextField(blank=True, null=True)),
                ('badge_criteria_url', models.URLField(blank=True, null=True)),
                ('badge_image_url', models.URLField(blank=True, null=True)),
                ('image', models.FileField(blank=True, upload_to='uploads/badges')),
                ('issuer_name', models.CharField(max_length=255)),
                ('issuer_url', models.URLField()),
                ('issuer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('issuer_image_url', models.URLField(blank=True, null=True)),
                ('issued_on', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('recipient_identifier', models.CharField(db_index=True, max_length=768)),
                ('recipient_type', models.CharField(choices=[('email', 'email'), ('openBadgeId', 'openBadgeId'), ('telephone', 'telephone'), ('url', 'url')], default='email', max_length=255)),
                ('acceptance', models.CharField(choices=[('Unaccepted', 'Unaccepted'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Accepted', max_length=254)),
                ('revoked', models.BooleanField(default=False)),
                ('revocation_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('original_json', jsonfield.fields.JSONField()),
                ('hashed', models.BooleanField(default=True)),
                ('salt', models.CharField(blank=True, default=None, max_length=254, null=True)),
                ('narrative', models.TextField(blank=True, null=True)),
                ('verification_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Imported Badge Assertion',
            },
        ),
        migrations.CreateModel(
            name='ImportedBadgeAssertionExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('original_json', models.TextField(blank=True, default=None, null=True)),
                ('importedBadge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='issuer.importedbadgeassertion')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
