# Generated by Django 3.2 on 2025-05-12 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuer', '0075_importedbadgeassertion_importedbadgeassertionextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='criteria',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
