FROM python:3.8.14-slim-buster

RUN mkdir /badgr_server
WORKDIR /badgr_server

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y default-libmysqlclient-dev \
                       python3-dev \
                       python3-cairo \
                       build-essential \
                       xmlsec1 \
                       libxmlsec1-dev \
                       pkg-config

RUN pip install uwsgi

COPY requirements.txt              /badgr_server
RUN pip --timeout=1000 install -r requirements.txt
RUN pip --timeout=1000 install debugpy
