# Generated by Django 3.2 on 2025-02-27 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0024_auto_20200608_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltchaChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salt', models.CharField(max_length=24)),
                ('challenge', models.CharField(max_length=64)),
                ('signature', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('solved_by_ip', models.GenericIPAddressField(blank=True, null=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='altchachallenge',
            index=models.Index(fields=['used'], name='mainsite_al_used_f638a8_idx'),
        ),
        migrations.AddIndex(
            model_name='altchachallenge',
            index=models.Index(fields=['created_at'], name='mainsite_al_created_2be6dc_idx'),
        ),
    ]
